### PR TITLE
Space Fix

### PR DESCRIPTION
**Pull request by fancythedeveloper**
`ERROR 1064 (42000) at line 791: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '=71' at line 2` Fix, pretty sure I forgot to add some spaces

### CODE REVIEW

**Comment by fancythedeveloper** [comment]
Someone should probably test this before merging lol.

**Comment by Intelligent-Cat** [comment]
didnt spaces cause this when you tested

**Comment by fancythedeveloper** [comment]
Wasn't it lack of spaces? I don't remember.

**Comment by Jecket22** [comment]
Spacing doesn't fix it, I'll look into it myself though, seems to be a different MySQL error

**Pull request closed without merging**
