### PR TITLE
database.sql fix!

### PR DESCRIPTION
**Pull request by RobloxNationGaming**
I fixed it :D

### CODE REVIEW

**Comment by RobloxNationGaming** [comment]
Look
Screenshot_2021-05-16-22-21-21-30

**Comment by Jecket22** [comment]
Is this on a fresh or a pre-used database? Please note that this fork is not specifically made to be compatible for Cvolton's version.

**Comment by RobloxNationGaming** [comment]
No!, find put cvolton's database.sql

**Comment by Jecket22** [comment]
Oh please don't mix those up. Again, this is not made to work with Cvolton's version. I'll have to reject this for that matter.

**Comment by RobloxNationGaming** [comment]
Ok NVM...

**Comment by tzt345** [comment]
Wtf

**Pull request closed without merging**
